# Generated by Django 4.1.3 on 2023-03-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Gst_app',
        ),
    ]
